### ISSUE TITLE
Fonts...

### ISSUE THREAD

**Issue by cycomachead** [beautyjoy/llab#29]
So, yeah, we should fix this mess. :P

Here's the current list of font options:

``` CSS
.dumbfonts {
  font: 1em Helvetica, Arial, sans-serif;
  font-family: "Helvetica Neue", Helvetica, "Gill Sans", Arial;
  font: 500 15px/1.7 "Times New Roman", Times, serif;
  font: 500 30px Tahoma, Geneva, sans-serif;
  font: bold 1.5em Georgia, serif;
  font-family: "Helvetic Neue", Helvetica, Arial, sans-serif;
  font: .9em "Palatino Linotype", "Book Antiqua", 'Palatino', serif;
  font: 900 26px "Palatino Linotype", "Book Antiqua", "Palatino", serif;
  font-family: Georgia, "Times New Roman", Times, serif;
  font: 600 .9em "Courier New", Courier, monospace;
  font-family: Arial, Helvetica, Arial;
}
```
- We should banish the combined font line since it's a pain to share stuff
- We have such a mix of fonts and these things don't make sense...
  Proposal:
- nice sans-serif set for reading and main content
- Serif stuff for titles?
- We need a good monospace font.
- I would like to use the VAGRounded font somewhere - as it's what Dan uses for his slides and I think it could create a nice theme. (Maybe).
